### ISSUE TITLE
Game freezes when in help screen

### ISSUE THREAD

**Issue by gwathlobal** [AllureOfTheStars/Allure#72] opened 2017-09-04 22:46 UTC
Whenever I enter help from the menu using '?' shortcut, the game freezes.
If I get to help by navigating the menu using arrow keys and then pressing enter - the game works fine.

Also sometimes freezing occurs when I scroll through the menu using 'space' or 'page up' button. This seems rather random, I have not found the pattern.

**Comment by gwathlobal** [comment] 2017-09-05 06:09
After playing a bit, I have to say that freezes also occur randomly, when I play the game.

I use 6.0.0 Win x64 version downloaded from the Releases section.

**Comment by Mikolaj** [comment] 2017-09-06 09:44
Hi! Thank you for the report --- I was just wondering if I managed to fix that bug in the dev version (because I can't reproduce it). It's probably caused by some SDL backends on windows not being thread-safe, so I restricted all SDL calls to the main thread. 

Could you try the following build? It's a 0.6.1.0 prerelease and if you confirm it works, it will probably be released very soon as is:

https://ci.appveyor.com/project/Mikolaj/allure/build/artifacts

**Comment by gwathlobal** [comment] 2017-09-06 17:28
Ok, first things first - when I started the game I had this in the second console window, though the game started normally

Restore failed. The old file moved aside. The error message is: Data.Binary.Get.runGet at position 67219: not enough bytes CallStack (from HasCallStack):   error, called at libraries\binary\src\Data\Binary\Get.hs:351:5 in binary-0.8.5.1:Data.Binary.Get
Restore failed. The old file moved aside. The error message is: Data.Binary.Get.runGet at position 36857: not enough bytes CallStack (from HasCallStack):   error, called at libraries\binary\src\Data\Binary\Get.hs:351:5 in binary-0.8.5.1:Data.Binary.Get
Restore failed. The old file moved aside. The error message is: Data.Binary.Get.runGet at position 37756: not enough bytes CallStack (from HasCallStack):   error, called at libraries\binary\src\Data\Binary\Get.hs:351:5 in binary-0.8.5.1:Data.Binary.Get
Restore failed. The old file moved aside. The error message is: Data.Binary.Get.runGet at position 35771: Not a valid Unicode code point! CallStack (from HasCallStack):   error, called at libraries\binary\src\Data\Binary\Get.hs:351:5 in binary-0.8.5.1:Data.Binary.Get

The menu seemed to work just fine. I scrolled back and forth, exited and entered again using various means.

The game itself seems to work fine as well. I was rather quickly killed, but in the previous build, I did not even get there :)

**Comment by Mikolaj** [comment] 2017-09-06 19:10
Yeah, the "Restore failed. The old file moved aside" is normal, because savegames from previous version are not compatible, so they are renamed to bkp.* (not just deleted in case you want to continue playing them using old version of the game, or in case the restore failure is caused by a bug, not by version change).

Great new about lack of crashes. You will probably still experience an occasional crash when you keep the game spinning (in automated mode) and suspend/restore the machine or run a full-screen application simultaneously or something similar. But by default the game auto-saves every few dozen turns, so not much should be lost.

Thanks again and have fun. :)

**Comment by Mikolaj** [comment] 2017-09-06 19:13
BTW, you may try lower difficulty --- there's no shame in that, the default difficulty is rather punishing until you gather a sizeable bag of tricks and learn to conserve every HP (regeneration only via rare items or temporary regeneration via consumables).

**Comment by Mikolaj** [comment] 2017-09-07 20:22
Allure 0.6.1.0 is out! It's completely the same version you've got. Closing the issue. Cheers!

**Closed by Mikolaj** 2017-09-07 20:22 UTC
